##############################################   User Auth routes Tests    ################################
# register test
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "firstName": "Jeff",
    "lastName": "Bezos",
    "email":"jeff@gmail.com",
    "password": "123456Jeff.",
    "role": 2
}

# "password": "123456Name."
#####################################

##### Login test
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"heimer@gmail.com",
    "password": "123456Heimer."
}

##############################################   Order routes Tests    ################################
### Get all the orders 
GET http://localhost:8000/api/getOrders

### Get orders by User
Get http://localhost:8000/api/getUserOrders/630691b132c19f793cfa3f4c

##### Create order 
POST http://localhost:8000/api/create/630691b132c19f793cfa3f4c
Content-Type: application/json

{
  "start_lat": 468,
  "start_lng": 312,
  "end_lat": 872,
  "end_lng": 2555555,
  "distance": 454545,
  "time": 32323
}

#### Update order
PUT http://localhost:8000/api/update/630f6d6f9e74853ab83184b4
Content-Type: application/json

{
  "start_lat": 8,
  "start_lng": 2,
  "end_lat": 95,
  "end_lng": 7,
  "distance": 234463,
  "time": 6012
}

#### delete order
DELETE http://localhost:8000/api/delete/630e9d3ecdf135a36a2b2a01


###################################################       Driver routes Tests       ################################
# get request 
GET http://localhost:8000/api/driver/getRequest/631cb42d85e7cbf68c6e603c

###
# get request 
POST http://localhost:8000/api/driver/confirmRequest

###
# driver Availabiity 
PUT http://localhost:8000/api/driver/availability/63357d6f7def2b51fd6fd7fb
Content-Type: application/json

{
  "availability": true
}
### 63357d6f7def2b51fd6fd7fb
# driver Location 
PUT http://localhost:8000/api/driver/location/63357d6f7def2b51fd6fd7fb
Content-Type: application/json

{
  "location": "[000333,055553]"
}

#### driver: Order delivered  
PATCH http://localhost:8000/api/driver/confirmRequest/634b585cbc8ec16832feea76
Content-Type: application/json

{
  "delivered": true
}

#### Get driver Profile Photo
GET http://localhost:8000/api/driver/profilePhoto/6368cf9724bca6e15dcbebc3

#### driver Profile Info 
PUT http://localhost:8000/api/driver/updateProfileInfo/6368cf9724bca6e15dcbebc3
Content-Type: application/json

{
  "email": "kermit@gmail.com",
  "password": "123456Kermit."
}
###################################################       Users routes Tests       ################################
# get all users 
GET http://localhost:8000/api/admin/getUsers

###
# get all drivers 
GET http://localhost:8000/api/admin/getDrivers

###
# get all Orders
GET http://localhost:8000/api/admin/getOrders

###
# delete user
DELETE http://localhost:8000/api/admin/deleteUser/630652de2d8d67be54c5c240

###
# delete driver
DELETE http://localhost:8000/api/admin/deleteDriver/631b53668eb8528548163e7a