##############################################   User Auth routes Tests    ################################
# register test
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "firstName": "Senna",
    "lastName": "Black",
    "email":"senna@gmail.com",
    "password": "123456Senna.",
    "isUser": true
}

# "password": "123456Name."
#####################################

##### Login test
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "firstName": "sawssen",
    "lastName": "jandoubi",
    "email":"sawssen@gmail.com",
    "password": "123456Sawssen."
}

##############################################   Order routes Tests    ################################
### Get all the orders 
GET http://localhost:8000/api/getOrders

### Get orders by User
Get http://localhost:8000/api/getUserOrders/630691b132c19f793cfa3f4c

##### Create order 
POST http://localhost:8000/api/create/630691b132c19f793cfa3f4c
Content-Type: application/json

{
  "start_lat": 468,
  "start_lng": 312,
  "end_lat": 872,
  "end_lng": 2555555,
  "distance": 454545,
  "time": 32323
}

#### Update order
PUT http://localhost:8000/api/update/630f6d6f9e74853ab83184b4
Content-Type: application/json

{
  "start_lat": 8,
  "start_lng": 2,
  "end_lat": 95,
  "end_lng": 7,
  "distance": 234463,
  "time": 6012
}

#### delete order
DELETE http://localhost:8000/api/delete/630e9d3ecdf135a36a2b2a01


##############################################   Driver routes Tests    ################################
# get request 
GET http://localhost:8000/api/driver/getRequest

###
# get request 
POST http://localhost:8000/api/driver/confirmRequest